add ipv6 for skidoo
redhat-partner-solutions/vse-carslab-hub pull request #53
Opened 2023-04-20 02:54 UTC by novacain1

This PR:

1. Adds IPv6 support for the Skidoo Single Node OpenShift cluster.  We should always test with IPv6
2. Streamlines semantics of siteconfig a bit, removes quotes where not necessary
3. Adds VSE ssh key

2023-04-20 10:41 UTC, natifridman requested changes
Please fix lint errors

2023-04-24 10:44 UTC, natifridman approved these changes
LGTM, please wait for #54 before merge. I would like to test the cherry-pick in this PR

2023-04-25 10:02 UTC, nocturnalastro approved these changes

2023-04-25 10:23 UTC, natifridman commented
/cherry-pick cars2

2023-04-25 10:23 UTC, merged